Granja:
- 4 cabezas
- 6 patas

Tiene:
- Pollitos (2 patas)
- Cerdos (4 patas)

¿Cuantos animales hay de cada tipo?

NC = 4
NP = 6

x = num cerdos
y = num pollos

x*1 + y*1 = NC -> x + y = 4
x*4 + y*2 = NP -> 4x + 2y = 6


In [1]:
import numpy as np

a = np.array([1,1],[4,2])

b = np.array([4,6])

X = np.array([x,y])

a * X = b

In [10]:
# a = np.array([[1,1],[4,2]])
# print(a)
# b = np.array([4,6])
# print(b)

# X = a.linalg.inv() * b.transpose()
# X

[[1 1]
 [4 2]]
[4 6]


AttributeError: 'numpy.ndarray' object has no attribute 'linalg'

In [17]:
A = np.mat(np.array([[4,2],[1,1]]))
b = np.mat(np.array([8,3])).T
X = A.I*b
X

matrix([[1.],
        [2.]])

# PCA

In [25]:
A = np.matrix(np.array([[3,0],[0,3]]))
A

matrix([[3, 0],
        [0, 3]])

In [26]:
v = np.matrix(np.array([1,1])).T
v

matrix([[1],
        [1]])

In [24]:
# Buscamos: A*v = lamb*v

In [27]:
A*v

matrix([[3],
        [3]])

In [28]:
3*v

matrix([[3],
        [3]])

Se cumple pues que con el escalar lambda=3 (valor propio o eigen-value) multiplicado por el vector propio (o eigen-vector) se obtiene el mismo resultado que la matriz original A

Con el PCA se pretende reducir la complejidad de una matriz original a sus componentes principales y "direcciones preferentes"